spring:
  application:
    name: banking-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/banking-service-demo-project/config-server-banking-properties
          clone-on-start: true

server:
  port: 9094

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9091/eureka
  instance:
    prefer-ip-address: true
